class MobileControls{
    constructor(){
        this.left=false
        this.right=false
        this.up=false
        this.down=false
        this.turnAcel=0
        this.rightSensor=new rightSensor(10,10)
    }
    update(){
        this.rightSensor.update()
        if(this.rightSensor.changeX>20){
            this.right=true
        }else{
            this.right=false
        }
        if(this.rightSensor.changeX<-20){
            this.left=true
        }else{
            this.left=false
        }
        if(this.rightSensor.changeY>20){
            this.up=true
        }else{
            this.up=false
        }
        if(this.rightSensor.changeY<-20){
            this.down=true
        }else{
            this.down=false
        }
        this.turnAcel=(this.rightSensor.changeX/80)/100
        this.turnAcel=Math.abs(this.turnAcel)
    }
}